---
- name: Install and Configure Mirror Registry
  hosts: mirror-registry 
  become: yes
  vars:
    - registry_admin_username: ''
    - registry_admin_password: ''
    - registry_host_fqdn: ''
    - registry_host_port: 5000
    - registry_certs_dir: '/opt/registry/certs'
    - registry_data_dir: '/opt/registry/data'
    - registry_auth_dir: '/opt/registry/auth'
    - registry_container_name: "mirror-registry"
    - use_containeried_registry: true
    - secure_registry: true
    - registry_container_port: '5000'
    - enable_authz_on_registry: true
    - enable_auth_on_registry: true
    - registry_certcsrfile: 'registry.csr'
    - registry_certfile: 'registry.crt'
    - registry_certkeyfile: "registry.key"
    - registry_authzfile: 'registry_passwd'
    - registry_authzrealm: "Registry Realm"
    - registry_container_image: "docker.io/library/registry:2"
    - generate_selfsigned_registry_certfiles: true 
    - cert_country: "US"
    - cert_state: "CO"
    - cert_locality: "Aurora"
    - cert_org: "Red Hat"
    - cert_org_unit: "OCP"

  roles:
  - install-and-configure-mirror-registry


- name: Mirror content and copy to media to use for disconnected install 
  hosts: localhost
  become: yes
  vars:
    - registry_certfile: 'registry.crt'
    - ocp_client_release: '4.3.2'
    - ocp_release: '4.3.0'
    - registry_host_fqdn: ''
    - mirror_registry_fqdn_port:
    - ocp_release: '4.3.2-x86_64'
    - release_name: ocp-release
    - mirror_registry_fqdn: ""
    - mirror_registry_port: "5000"
    - mirror_registry_ca:
    - mirror_registry_username: 
    - mirror_registry_password:
    - local_repository: 'ocp4/openshift4'
    - local_secret_json:
    - mirror_registry_pullsecret:
    - ocp_registries_pullsecret:
    - content_source_output:
    - product_repo: 'openshift-release-dev'
    - local_mirrored_contents_store_dir:

  roles:
  - sync-content-for-disconnected-ocp-install
